name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pip install pre-commit
          python -m pip install flake8

      - name: pre-commit
        run: |
          pre-commit run --all-files

      - name: Check requirements.txt is up to date
        run: |
          pipenv requirements --hash >requirements.txt.new
          diff -usw requirements.txt requirements.txt.new

      - name: Install requirements
        run: pipenv sync
